name: Build and Publish package to GitHub Packages
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY: europe-docker.pkg.dev

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_PASSWORD
          cache: 'maven'
      - name: Get version
        id: version
        run: |
          echo "parsing version from ref '$GITHUB_REF'"

          VERSION=$(echo "$GITHUB_REF"  | sed -e "s|refs/tags/||g" | sed -E 's/v?([0-9]+)\.([0-9]+)\.([0-9]+)(-[a-zA-Z]+(\.[0-9]+)?)?/\1.\2.\3\4/g')
          echo "version: '$VERSION'"

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Update Version
        run: |
          echo "updating version to '$VERSION'"
          mvn -B versions:set "-DnewVersion=$VERSION"
      - name: Publish package
        run: |
          echo -n "$MAVEN_GPG_KEY" | gpg --import --batch
          mvn --batch-mode -Prelease deploy
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_TR_PASSPHRASE }}
          MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_TR_KEY }}
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      # release the corresponding docker image
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Configure Docker for GAR
        run: gcloud auth configure-docker europe-docker.pkg.dev --quiet
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - id: buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Image
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          make dist RELEASE_TAG=v$VERSION
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/epa4all-rest-service/')
        with:
          name: ${{ steps.version.outputs.version }}
          body: |
            Docker image: `europe-docker.pkg.dev/oviva-pkg/ovi/epa4all-rest-service:v${{ steps.version.outputs.version }}`
          files: |
            target/epa4all-rest-service.jar
